name: react-ts-template-prod # TODO: указать свое имя

services:
  caddy:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    image: caddy
    container_name: caddy_container
    ports:
      # - "80:80"
      # - "443:443"
      - 8081:80
    restart: unless-stopped
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
