name: react-ts-template-prod # TODO: указать свое имя

services:
  caddy:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    image: caddy
    container_name: caddy_container
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: backend_image
    container_name: prod_backend
    env_file:
      - ./backend/.env
    expose:
      - "3333"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
