services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: prod_frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
